waldo_exemple:
    resource: "@WaldoExempleBundle/Controller/"
    type:     annotation
    prefix:   /

waldo_open_id_connect_relying_party:
    resource: "@WaldoOpenIdConnectRelyingPartyBundle/Resources/config/routing.xml"
    prefix:   /oic/

