_oic_rp:
    resource: "@WaldoOpenIdConnectRelyingPartyBundle/Resources/config/routing.yml"

waldo_exemple:
    resource: "@WaldoExempleBundle/Controller/"
    type:     annotation
    prefix:   /
    
login_check:
    path: /login_check
    