waldo_oic_rp_redirect:
    resource: "@WaldoOpenIdConnectRelyingPartyBundle/Resources/config/routing/redirect.xml"
    prefix:   /connects

waldo_oic_rp_login:
    resource: "@WaldoOpenIdConnectRelyingPartyBundle/Resources/config/routing/login.xml"
    prefix:   /login

waldo_exemple:
    resource: "@WaldoExempleBundle/Controller/"
    type:     annotation
    prefix:   /