security:  
    providers:
        OICUserProvider: 
            id: waldo_oic_rp.user.provider
            

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            openidconnect:
                always_use_default_target_path: false
                default_target_path: /private/other
                target_path_parameter: ~
                login_path: /private
                use_referer: ~
                create_users: true

                
    
    access_control:
        - { path: ^/private, roles: ROLE_OIC_USER }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }