security:
    providers:
        OICUserProvider: 
            id: waldo_oic_rp.user.provider
            

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            openidconnect: ~
    
    access_control:
        - { path: ^/private, roles: ROLE_OIC_USER }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }